### ISSUE TITLE
esm_runscript crash when scenario is added

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_runscripts#172]
With the latest version (on HLRN4):
```
glogin5:~/esm/esm_tools/runscripts/foci $ esm_versions check
+---------------------+-----------+---------------------------------------------------+----------+----------------------------+
| package_name        | version   | file                                              | branch   | tags                       |
|---------------------+-----------+---------------------------------------------------+----------+----------------------------|
| esm_calendar        | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |                            |
| esm_database        | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |                            |
| esm_environment     | 5.1.1     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |                            |
| esm_master          | 5.1.3     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |                            |
| esm_motd            | 5.0.2     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |                            |
| esm_parser          | 5.1.7     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |                            |
| esm_plugin_manager  | 5.0.1     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |                            |
| esm_profile         | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |                            |
| esm_rcfile          | 5.1.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |                            |
| esm_runscripts      | 5.1.27    | /home/shkifmsw/esm/esm_runscripts                 | release  | v5.1.27-2-g9405139         |
| esm_tools           | 5.0.12    | /home/shkifmsw/esm/esm_tools                      | geomar   | v5.0.12-161-ge989858-dirty |
| esm_version_checker | 5.1.5     | /home/shkifmsw/.local/lib/python3.7/site-packages |          |                            |
+---------------------+-----------+---------------------------------------------------+----------+----------------------------+
```
I added 
```
echam:
   scenario: 1percCO2
```
(I want to prepare a 1pct CO2 scenario for a colleague) to our FOCI default setup. If I add the `scenario: 1percCO2` to the ECHAM6 block (note: If I add it to the `general: ` section, nothing happens), esm_runscripts crashed with the following:
```
glogin5:~/esm/esm_tools/runscripts/foci $ esm_runscripts -e f1pctCO2 FOCI-SW1pctCO2.yaml -c
************************************************************************************
Message found for package esm_tools version 5.0.12:

"The new minor release 5.1 is now available!
This minor release include no new models or couple setups but new features to the following packages:
    - esm_master
    - esm_parser
    - esm_environment
    - esm_rcfiles
    - esm_version_checker
    - esm_tools
To get this updates simply run 'esm_versions upgrade'.

NOTE TO DEVELOPERS AND ADVANCE USERS: if you intend to use an branch of 'esm_tools' that is not 'release'
you might face conflicts with the new 'esm_environment'. These conflicts are easily solved by copying the
new machine files into your 'esm_tools' branch (make sure you commit the changes in your branch before
copying the machine files over). Feel free to contact us if you need any assistance with this issue.
"

Upgrade this package by typing:              esm_versions upgrade esm_tools
Upgrade all packages by typing:              esm_versions upgrade
************************************************************************************
First year, checking if we need to compile...

================================================================================
STARTING SIMULATION JOB!
Experiment ID = f1pctCO2
Setup = foci
This setup consists of:
- echam
- nemo
- xios
- oasis3mct
- jsbach
- hdmodel
Experiment is installed in:
       /home/shkifmsw/esm/esm-experiments//f1pctCO2
================================================================================

Traceback (most recent call last):
  File "/home/shkifmsw/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/cli.py", line 225, in main
    Setup()
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/sim_objects.py", line 55, in __call__
    self.compute(*args, **kwargs)
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/sim_objects.py", line 89, in compute
    self.config = compute.run_job(self.config)
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/compute.py", line 36, in run_job
    config = evaluate(config, "compute", "compute_recipe")
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/helpers.py", line 101, in evaluate
    framework_recipe, framework_plugins, config
  File "/home/shkifmsw/.local/lib/python3.7/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/filelists.py", line 907, in assemble
    config = complete_targets(config)
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/filelists.py", line 134, in complete_targets
    config[model][filetype + "_sources"][categ]
  File "/sw/tools/python/anaconda3/2019.03/skl/lib/python3.7/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not dict
```
What goes wrong here? I did a git pull on my develop install of esm_runscripts to have the latest release (see output of `esm_versions check` above)

**Comment by denizural** [comment]
This looks like the problem I solved for the HIST scenario. I have a `hist_fixed` branch (which I will merge). Could you please try  a check run (`--check`) with that Sebastian?

**Comment by seb-wahl** [comment]
Thanks for the quick reply. Unfortunately the same error:
```
....

Traceback (most recent call last):
  File "/home/shkifmsw/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/cli.py", line 202, in main
    Setup()
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/sim_objects.py", line 50, in __call__
    self.compute(*args, **kwargs)
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/sim_objects.py", line 84, in compute
    self.config = compute.run_job(self.config)
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/compute.py", line 32, in run_job
    config = evaluate(config, "compute", "compute_recipe")
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/helpers.py", line 49, in evaluate
    framework_recipe, framework_plugins, config
  File "/home/shkifmsw/.local/lib/python3.7/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/filelists.py", line 941, in assemble
    config = complete_targets(config)
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/filelists.py", line 126, in complete_targets
    config[model][filetype + "_sources"][categ]
  File "/sw/tools/python/anaconda3/2019.03/skl/lib/python3.7/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not dict
```
```
esm_runscripts
├─ version: 5.1.12
├─ path: /home/shkifmsw/esm/esm_runscripts
├─ branch: hist_fixed
└─ tags: v5.0.17-78-gbe54dbd
```

**Comment by denizural** [comment]
Could you please send me your runscript Sebastian? I can try that on Mistral. Currently, I don't have a HLRN account (applied today). I can debug that on Mistral or Ollie.

**Comment by seb-wahl** [comment]
I think I at least understand why it does not work. We use JSBACH 3.20p1 where nothing is configured for `1percCO2` (see `configs/components/jsbach/jsbach.yaml`). But I would expect that the tools tell me that files are missing or that some defaults are used but not a crash. If I add a simple `print` statement just before the error occurs I figured that some placeholders are not resolved probably because of what I mentioned above:
```
Experiment is installed in:
       /home/shkifmsw/esm/esm-experiments//f1pctCO2
================================================================================

/home/shkifmsw/esm/esm-experiments//f1pctCO2/run_18500101-18501231/config/oasis3mct//namcouple
/scratch/usr/shkifmsw/foci_input2/JSBACH/input/r0010/T63/New_Hampshire_LCC/hist_harvest/LUH_harvest_T63_1850.nc
/scratch/usr/shkifmsw/foci_input2/JSBACH/input/r0010/T63/New_Hampshire_LCC/hist_harvest/LUH_harvest_T63_1950.nc
{'/scratch/usr/shkifmsw/foci_input2/JSBACH/input/r0010/T63/New_Hampshire_LCC/hist_harvest/LUH_harvest_T63_1850.nc': {'to': 1850}, '/scratch/usr/shkifmsw/foci_input2/JSBACH/input/r0010/T63/New_Hampshire_LCC/hist_harvest/LUH_harvest_T63_@YEAR@.nc': {'from': 1851}}
Traceback (most recent call last):
```
I placed a copy of my runscripts at `/work/bb0519/b350071/FOCI-SW1pctCO2.yaml` on mistral

**Comment by denizural** [comment]
Thanks, I will have look now. Yes, therefore this passes a `dict` instead of a `str`.

**Comment by denizural** [comment]
Pull request https://github.com/esm-tools/esm_runscripts/pull/174 solves this issue. I will close this now.

**Comment by seb-wahl** [comment]
Hi @denizural 
unfortunately your last commit broke hist_fixed for our "multiline" entries in the yamls. 
```
    "ozone_hist_scenario":
                "${forcing_dir}/ozone/${resolution}_ozone_historical_1850.nc":
                        to: 1850
                "${forcing_dir}/ozone/${resolution}_ozone_historical_@YEAR@.nc":
                        from: 1851
                        to: 2014
                "${forcing_dir}/ozone/${resolution}_ozone_${scenario}_@YEAR@.nc":
                        from: 2015
```
I produced a fix: 
https://github.com/esm-tools/esm_runscripts/compare/85a113a..e8112e8 
I will do a pull request for hist_fixed into release now.

**Comment by seb-wahl** [comment]
Wait the pull request ist still there...

**Comment by seb-wahl** [comment]
As the pull request is still there, I close the issue again.
