### ISSUE TITLE
Numerical experiment ID leads to str (not "int") to str

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_runscripts#71]
If you set the name of an experiment to a number. e.g.
`esm_runscripts awicm3-ollie-TCO159L91-CORE2.yaml -e 1850 --open-run`
The ID will be interpreted as an integer rather than a string, leading to the following error message:

```
Traceback (most recent call last):
  File "/home/ollie/jstreffi/.local/bin/esm_runscripts", line 30, in <module>
    sys.exit(load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')())
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/cli.py", line 199, in main
    Setup = SimulationSetup(command_line_config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/sim_objects.py", line 42, in __init__
    self.config = prepare.run_job(self.config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/prepare.py", line 5, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/helpers.py", line 69, in evaluate
    framework_recipe, framework_plugins, config
  File "/home/ollie/jstreffi/.local/lib/python3.7/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 130, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/prepare.py", line 648, in initialize_coupler
    + "/"
TypeError: can only concatenate str (not "int") to str
```
I would suggest that whatever follows the -e flag should always be interpreted as a string regardless of the actual characters involved.

This run was done on the latest version of develop 080d79d0a99626cdddca6df5af53443d1d6e0d57

**Comment by JanStreffing** [comment]
```
+---------------------+-----------+---------------------------------------------------------+----------------+--------------------------+
| package_name        | version   | file                                                    | branch         | tags                     |
|---------------------+-----------+---------------------------------------------------------+----------------+--------------------------|
| esm_calendar        | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                |                          |
| esm_database        | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                |                          |
| esm_environment     | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                |                          |
| esm_master          | 5.0.1     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                |                          |
| esm_motd            | 5.0.1     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                |                          |
| esm_parser          | 5.0.3     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                |                          |
| esm_plugin_manager  | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                |                          |
| esm_profile         | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                |                          |
| esm_rcfile          | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                |                          |
| esm_runscripts      | 5.0.13    | /home/ollie/jstreffi/esm_runscripts                     | develop        | v5.0.13-26-g080d79d      |
| esm_tools           | 5.0.11    | /home/ollie/jstreffi/esm_tools                          | feature/awicm3 | v5.0.8-43-g9d765dd-dirty |
| esm_version_checker | 5.1.2     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                |                          |
+---------------------+-----------+---------------------------------------------------------+----------------+--------------------------+

```
