### ISSUE TITLE
use scontrol to get list of nodes

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_runscripts#85]
On the way to implementing MPI + MPI/OMP I made the following test branch: https://github.com/esm-tools/esm_runscripts/commit/df8e88b22430f4271b148d18dca54fb3cb39df01

I'm having trouble with:
```
            state_command = ["scontrol show hostnames $((SLURM_JOB_NODELIST))"] #$SLURM_JOB_NODELIST"]
            scontrol_output = subprocess.Popen(state_command, stdout = subprocess.PIPE, stderr = subprocess.PIPE).communicate()[0]
```
When I try to run the model i get:
```
Jan was here
Jan was here
Jan was here
And here
Traceback (most recent call last):
  File "/home/ollie/jstreffi/.local/bin/esm_runscripts", line 30, in <module>
    sys.exit(load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')())
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/cli.py", line 202, in main
    Setup()
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/sim_objects.py", line 50, in __call__
    self.compute(*args, **kwargs)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/sim_objects.py", line 84, in compute
    self.config = compute.run_job(self.config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/compute.py", line 32, in run_job
    config = evaluate(config, "compute", "compute_recipe")
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/helpers.py", line 49, in evaluate
    framework_recipe, framework_plugins, config
  File "/home/ollie/jstreffi/.local/lib/python3.7/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 130, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/compute.py", line 80, in add_batch_hostfile
    config["general"]["batch"].calc_requirements(config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/batch_system.py", line 33, in calc_requirements
    return self.bs.calc_requirements(config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/slurm.py", line 125, in calc_requirements
    start_proc, end_proc = self.mini_calc_reqs(config, model, hostfile, start_proc, end_proc)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/slurm.py", line 101, in mini_calc_reqs
    scontrol_output = subprocess.Popen(state_command, stdout = subprocess.PIPE, stderr = subprocess.PIPE).communicate()[0]
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/global/AWIsoft/intel-python/2020.2.902/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'scontrol show hostnames $((SLURM_JOB_NODELIST))': 'scontrol show hostnames $((SLURM_JOB_NODELIST))'
```

It's a problem of options, as the tools will wait for options-input when i try to run scontrol without options. One problem I can already see is that this command should be executet once them model is on the queue. In the ksh tools the whole slurm file building was not done on the login node unless you ran a check run. Is it possible to call the whole slurm file business after submit?

**Comment by pgierz** [comment]
you need `shell=True`

**Comment by JanStreffing** [comment]
Ok I had a second try: https://github.com/esm-tools/esm_runscripts/commit/474d8a92c3d625590458b37bc8b54d2afbe03f88 also needs https://github.com/esm-tools/esm_tools/tree/slurm_hostlist_dist_arbitrary

```
+---------------------+-----------+---------------------------------------------------------+-------------------------------+----------------------+
| package_name        | version   | file                                                    | branch                        | tags                 |
|---------------------+-----------+---------------------------------------------------------+-------------------------------+----------------------|
| esm_calendar        | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_database        | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_environment     | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_master          | 5.0.1     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_motd            | 5.0.2     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_parser          | 5.0.5     | /home/ollie/jstreffi/esm_parser                         | develop                       | v5.0.5-7-g07e320c    |
| esm_plugin_manager  | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_profile         | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_rcfile          | 5.0.0     | /home/ollie/jstreffi/esm_rcfile                         | develop                       | v5.0.0-3-gc1d2efe    |
| esm_runscripts      | 5.0.16    | /home/ollie/jstreffi/esm_runscripts                     | slurm_hostlist_dist_arbitrary | v5.0.16-52-g474d8a9  |
| esm_tools           | 5.0.12    | /home/ollie/jstreffi/esm_tools                          | slurm_hostlist_dist_arbitrary | v5.0.12-126-ge424b3e |
| esm_version_checker | 5.1.2     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
+---------------------+-----------+---------------------------------------------------------+-------------------------------+----------------------+
```
The .sad file looks like this:




```
cd /work/ollie/jstreffi/runtime/awicm-3.1//HOS1/run_19900101-19900101/work/

#Creating hostlist for MPI + MPI&OMP heterogeneous parallel job
export SLURM_HOSTFILE=./hostlist
IFS=$'
'; set -f
listnodes=($(< <( scontrol show hostnames $SLURM_JOB_NODELIST )))
unset IFS; set +f
rank = 0
current_core = 0
current_core_mpi = 0
for model in ['fesom', 'rnfmap', 'oifs', 'oasis3mct']
do
    eval nb_of_cores=\${tasks_${model}}
    eval nb_of_cores=$((${nb_of_cores}-1))
    for nb_proc_mpi in `seq 0 ${nb_of_cores}`; do
    (( index_host = current_core / 36 ))
    host_value=${listnodes[${index_host}]}
    (( slot =  current_core % cores_per_compute_node ))
    echo '$host_value' >> hostlist
    (( current_core = current_core + omp_num_threads_compute_${model} ))
done

echo $(date +%c) : compute 1 1990-01-01T00:00:00 65311 - start >> /work/ollie/jstreffi/runtime/awicm-3.1//HOS1/log//HOS1_awicm3.log
time srun -l --kill-on-bad-exit=1 --cpu_bind=cores --multi-prog hostfile_srun &
process=$!
cd /work/ollie/jstreffi/runtime/awicm-3.1//HOS1/scripts/
esm_runscripts awicm3-ollie-TL159L60-CORE2.yaml -e HOS1 -t tidy_and_resubmit -p ${process} -j compute -v  --open-run
```
As you can see from my comments in the batch_system.py there are some things that I did not translate properly from the ksh version. The stuff in the slurm.py currently crashes with: 

```
Experiment is installed in:
       /work/ollie/jstreffi/runtime/awicm-3.1//HOS1
================================================================================

prog_fesom.sh
Traceback (most recent call last):
  File "/home/ollie/jstreffi/.local/bin/esm_runscripts", line 30, in <module>
    sys.exit(load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')())
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/cli.py", line 202, in main
    Setup()
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/sim_objects.py", line 50, in __call__
    self.compute(*args, **kwargs)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/sim_objects.py", line 84, in compute
    self.config = compute.run_job(self.config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/compute.py", line 32, in run_job
    config = evaluate(config, "compute", "compute_recipe")
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/helpers.py", line 49, in evaluate
    framework_recipe, framework_plugins, config
  File "/home/ollie/jstreffi/.local/lib/python3.7/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 130, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/compute.py", line 80, in add_batch_hostfile
    config["general"]["batch"].calc_requirements(config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/batch_system.py", line 33, in calc_requirements
    return self.bs.calc_requirements(config)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/slurm.py", line 133, in calc_requirements
    start_proc, end_proc = self.mini_calc_reqs(self,config, model, hostfile, start_proc, end_proc)
  File "/home/ollie/jstreffi/esm_runscripts/esm_runscripts/slurm.py", line 111, in mini_calc_reqs
    progname.write("(( slot = index % "+str(config("computer"["cores_per_node"]))+"))"+"\n")
TypeError: string indices must be integers
```

Help wanted. I'm at the TRR winterschool now but I can drop out for a quick chat if needed to explain what I'm trying to do here.

**Comment by JanStreffing** [comment]
```
+---------------------+-----------+---------------------------------------------------------+-------------------------------+----------------------+
| package_name        | version   | file                                                    | branch                        | tags                 |
|---------------------+-----------+---------------------------------------------------------+-------------------------------+----------------------|
| esm_calendar        | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_database        | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_environment     | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_master          | 5.0.1     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_motd            | 5.0.2     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_parser          | 5.0.5     | /home/ollie/jstreffi/esm_parser                         | develop                       | v5.0.5-7-g07e320c    |
| esm_plugin_manager  | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_profile         | 5.0.0     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
| esm_rcfile          | 5.0.0     | /home/ollie/jstreffi/esm_rcfile                         | develop                       | v5.0.0-3-gc1d2efe    |
| esm_runscripts      | 5.0.16    | /home/ollie/jstreffi/esm_runscripts                     | slurm_hostlist_dist_arbitrary | v5.0.16-54-g3c0b18a  |
| esm_tools           | 5.0.12    | /home/ollie/jstreffi/esm_tools                          | slurm_hostlist_dist_arbitrary | v5.0.12-127-g7586262 |
| esm_version_checker | 5.1.2     | /home/ollie/jstreffi/.local/lib/python3.7/site-packages |                               |                      |
+---------------------+-----------+---------------------------------------------------------+-------------------------------+----------------------+

```


I'm running `~/esm_tools/runscripts/awicm3/awicm3-ollie-TL159L60-CORE2.yaml` 
`esm_runscripts awicm3-ollie-TL159L60-CORE2.yaml -e MPI1 --open-run -c`

You will need to change:    ` base_dir: "/work/ollie/jstreffi/runtime/awicm-3.1/"`

Thank you!

**Comment by JanStreffing** [comment]
Solution found and implemented. To be merged still (https://github.com/esm-tools/esm_runscripts/pull/86), but I will close this here.
