### ISSUE TITLE
FileExistsError in monitoring

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_runscripts#87]
Sometimes, a run will crash due to a time out error. The solution is often to just resubmit the job.

However, if the user isn't careful about cleaning up, that in turn leads to:

```
set_logfile
-----------
 Traceback (most recent call last):
   File "/mnt/lustre02/work/ba0989/a270077/PalModII/mis3/.venv/bin/esm_runscripts", line 11, in <module>
     load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
   File "/mnt/lustre02/work/ba0989/a270077/PalModII/mis3/software/esm_runscripts/esm_runscripts/cli.py", line 193, in main
     Setup()
   File "/mnt/lustre02/work/ba0989/a270077/PalModII/mis3/software/esm_runscripts/esm_runscripts/sim_objects.py", line 54, in __call__
     self.tidy(*args, **kwargs)
   File "/mnt/lustre02/work/ba0989/a270077/PalModII/mis3/software/esm_runscripts/esm_runscripts/sim_objects.py", line 247, in tidy
     os.symlink(monitor_file_path, monitor_file_in_run)
 FileExistsError: [Errno 17] File exists: '/mnt/lustre02/work/ba0989/a270077/PalModII/mis3/experiments_production//T21G21O21_001/scripts//monitoring_file_20680101-20681231.out' -> '/mnt/lustre02/work/ba0989/a270077/PalModII/mis3/experiments_production//T21G21O21_001/run_2068010      1-20681231/scripts//monitoring_file.out'
    1 srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
```

It would be great if we could catch this and overwrite the file if it is already there.

**Comment by pgierz** [comment]
This was solved with Deniz's fix of symlinks
